/* categories */
export const CATEGORY_FIND_ALL_REQUEST = "CATEGORY_FIND_ALL_REQUEST";
export const CATEGORY_FIND_ALL_SUCCESS = "CATEGORY_FIND_ALL_SUCCESS";
export const CATEGORY_FIND_ALL_FAILURE = "CATEGORY_FIND_ALL_FAILURE";

/* post */
export const POST_FIND_ALL_REQUEST = "POST_FIND_ALL_REQUEST";
export const POST_FIND_ALL_BY_CATEGORY_REQUEST = "POST_FIND_ALL_BY_CATEGORY_REQUEST";
export const POST_FIND_ALL_SUCCESS = "POST_FIND_ALL_SUCCESS";
export const POST_FIND_ALL_FAILURE = "POST_FIND_ALL_FAILURE";
export const POST_FIND_ONE_REQUEST = "POST_FIND_ONE_REQUEST";
export const POST_FIND_ONE_SUCCESS = "POST_FIND_ONE_SUCCESS";
export const POST_FIND_ONE_FAILURE = "POST_FIND_ONE_FAILURE";
export const POST_INSERT_REQUEST = "POST_INSERT_REQUEST";
export const POST_INSERT_SUCCESS = "POST_INSERT_SUCCESS";
export const POST_INSERT_FAILURE = "POST_INSERT_FAILURE";
export const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
export const POST_UPDATE_VOTE_REQUEST = "POST_UPDATE_VOTE_REQUEST";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAILURE = "POST_UPDATE_FAILURE";
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";

/* comment */
export const COMMENT_FIND_ALL_BY_PARENT_ID_REQUEST = "COMMENT_FIND_ALL_BY_PARENT_ID_REQUEST";
export const COMMENT_FIND_ALL_SUCCESS = "COMMENT_FIND_ALL_SUCCESS";
export const COMMENT_FIND_ALL_FAILURE = "COMMENT_FIND_ALL_FAILURE";
export const COMMENT_UPDATE_VOTE_REQUEST = "COMMENT_UPDATE_VOTE_REQUEST";
export const COMMENT_INSERT_REQUEST = "COMMENT_INSERT_REQUEST";
export const COMMENT_INSERT_SUCCESS = "COMMENT_INSERT_SUCCESS";
export const COMMENT_INSERT_FAILURE = "COMMENT_INSERT_FAILURE";
export const COMMENT_UPDATE_REQUEST = "COMMENT_UPDATE_REQUEST";
export const COMMENT_UPDATE_SUCCESS = "COMMENT_UPDATE_SUCCESS";
export const COMMENT_UPDATE_FAILURE = "COMMENT_UPDATE_FAILURE";
export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST";

/* sort */
export const SORT = "SORT";


